### ISSUE TITLE
Build artifacts are inside of the git repository

### ISSUE THREAD

**Issue by AtlasHands** [preact-tech/preact_utilities#4]
This is a relatively minor issue, but it seems I've seen its typical split out the repos and utilize the GitHub "releases" functionality.

If the repository is mostly geared toward putting final builds into the GitHub repository, you may have to use something like BFG ([https://rtyley.github.io/bfg-repo-cleaner/](https://rtyley.github.io/bfg-repo-cleaner/)) and force push the repo so that old binaries are no longer pulled as more revisions are created.  Force pushing causes some grief if you are expecting to have active contributors.

Currently to pull this repo, I have to download 274 MiB of data:

```
Filtering content: 100% (2/2), 274.22 MiB | 28.86 MiB/s, done.
```

Pretty minor, I've just seen some people get mad even if there are images in the repo's git versioning.

I've also seen some repos (like OBS studio) suggest doing `git clone --depth=1 <url>` to speed up/reduce bandwidth during the build process -- so if you do plan on keeping binaries inside of the git repo that may be a good option too!

Thanks

**Comment by mikehamilton-preact-tech** [comment]
Hi @AtlasHands, this is a priority for us to clean up some of the infrastructure and fix items like this. We're hoping to get this cleaned up sometime in the next 2-3 weeks. Feel free to ping us for updates or any other questions.
